sonar.projectKey=join-a-groupchat_prototype-rtc-js
sonar.language=js
sonar.sources=server,consumer
sonar.tests=tests
<<<<<<< HEAD
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
=======
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info

sonar.sources=server,consumer
sonar.cpd.exclusions=**/*

sonar.host.url=https://sonarcloud.io
sonar.login=${SONAR_TOKEN}
>>>>>>> df1bb8650cdbf1b2ac6980f1532d9e271aa93a77
